version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.98.2
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: ${N8N_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_PASS}
      N8N_HOST: n8n.yellowstudyo.com.br
      N8N_PORT: 5678
      WEBHOOK_URL: https://n8n.yellowstudyo.com.br/
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: info
      N8N_LOG_OUTPUT: console
      EXECUTIONS_MODE: queue
      QUEUE_MODE: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    container_name: postgres-n8n
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  n8n_data:
  postgres_data:
  redis_data:
