name: Deploy n8n to VPS

on:
  push:
    branches: [main]
    paths:
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /opt/yellowstack/n8n
            git pull origin main
            docker-compose pull
            docker-compose down && docker-compose up -d
